<?php if($this->navMenu == true){ ?>
<h4>
	<a href="<?php echo $this->url('user');?>" class="btn btn-primary"><?php echo $this->translate('User'); ?></a>
<?php
	if (!$user = $this->identity()) {
?>
	<a href="<?php echo $this->url('login');?>" class="btn btn-primary"><?php echo $this->translate('Log in'); ?></a>
    <?php if($this->buttonRegister):?>
	<a href="<?php echo $this->url('registration');?>" class="btn btn-primary"><?php echo $this->translate('Sign up'); ?></a>
    <?php endif;?>
    <?php if($this->buttonForgotPassword):?>
	<a href="<?php echo $this->url('forgotten-password');?>" class="btn btn-primary"><?php echo $this->translate('Forgotten Password'); ?></a>
    <?php endif;?>
<?php
	}else{
?>
	<a href="<?php echo $this->url('editProfile');?>" class="btn btn-primary"><?php echo $this->translate('Edit Profile'); ?></a>
<?php } ?>
</h4>
<?php } ?>
