<?php
$this->headLink()->appendStylesheet($this->basePath('css/authentication.css'));
?>
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="img/avatar.png"/>
        <p id="profile-name" class="profile-name-card"></p>
        <?php echo $this->partial('cost-authentication/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
        <hr />
        <?php
        if($user = $this->identity()) {
         ?>
        <h3 style="float:left;">
        <button type="button" class="btn btn-default btn-lg">
           <span class="glyphicon glyphicon-user"></span>
        </button>
        &nbsp;<?php echo $this->translate('Welcome');?>
        <a href="<?php echo $this->url('editProfile');?>" class="text-info"><span class="zf-green"><?php echo $this->escapeHtml($user->getUsername()); ?></span></a>
        </h3>
        <a href="<?php echo $this->url('logout');?>" class="btn btn-lg btn-primary btn-block text-uppercase" style="float:right; margin-top: 25px"><?php echo $this->translate('Logout'); ?></a>
        <div></div>
        <?php  $this->translate('Welcome-Message');?>

        <?php
        }else{
        ?>
            <h4><?php echo $this->translate('Welcome');?><span  style="color: #FF8C00"><?php echo $this->translate('Guest');?></span>!</h4>
            <?php echo $this->translate('Please follow the buttons at the top to navigate through the system.');?>
        <?php
        }
        ?>
        </div>
</div>
