<?php
$this->headLink()->appendStylesheet($this->basePath('css/authentication.css'));
?>
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="img/avatar.png"/>
        <p id="profile-name" class="profile-name-card"></p>
        <h4><?php echo $this->translate('ChangePassword'); ?></h4>
        <!-- /widget-header -->
        <?php echo $this->partial('cost-authentication/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('changePassword'));
        $form->setAttribute('class', 'form-signin');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formText($form->get('currentPassword'));
        echo '<br />';
        echo $this->formPassword($form->get('newPassword'));
        echo '<br />';
        echo $this->formPassword($form->get('newPasswordConfirm'));
        echo '<br />';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
        <br/>
        <?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>

    </div>
</div>

