<?php
$this->headLink()->appendStylesheet($this->basePath('css/authentication.css'));
?>

<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="img/avatar.png"/>
        <p id="profile-name" class="profile-name-card"></p>
        <hr/>
        <!-- /widget-header -->
        <div class="col-sm-12">
            <?php echo $this->partial('cost-authentication/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
            <?php
            $form = $this->form;
            $username = $this->username;
            $email = $this->email;
            $displayname = $this->displayname;
            echo '<h5 class="zf-green"><strong>' . $this->translate('Your username') . ':</strong></h5>' . $username . ''; ?>
            <hr/>
            <?php
            echo '<h5 class="zf-green"><strong>' . $this->translate('Your password') . '</strong></h5>';
            ?><a href="<?php echo $this->url('changePassword'); ?>"
                 class="text-primary"><strong><?php echo $this->translate('Change password'); ?></strong></a>
            <hr/>
        </div>
        <div class="col-sm-12">
            <?php
            echo '<h5 class="zf-green"><strong>' . $this->translate('Your email') . ':</strong></h5>' . $email . ' ';
            ?>
            <a href="<?php echo $this->url('changeEmail'); ?>" class="text-primary"><strong>(<?php echo $this->translate('Change it'); ?>)</strong></a>
            <hr/>
            <?php
            echo '<h5 class="zf-green"><strong>' . $this->translate('Your display name') . ': </strong></h5>' . $displayname; ?>
        </div>
        <div class="col-sm-12">
            <?php
            $form->setAttribute('action', $this->url('editProfile'));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('displayName'));
            ?>
        </div>
        <div class="col-sm-12">
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
            <hr/>
        </div>
        <div class="col-sm-12">
            <br/>
            <?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>
        </div>
    </div>
</div>



