<?php
$this->headLink()->appendStylesheet($this->basePath('css/authentication.css'));
?>
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"/>
        <p id="profile-name" class="profile-name-card"></p>
        <?php echo $this->partial('cost-authentication/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
        <button type="button" class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-user"></span>
        </button>
        <?php echo $this->translate('ForgottenPassword') ?>
        </h3>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('forgotten-password'));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formText($form->get('usernameOrEmail'));?>
        <p id="profile-name" class="profile-name-card"></p>
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>

        <?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>
    </div>
</div>
